name: Push pipeline on OpenHEXA

on:
  workflow_dispatch:
    inputs:
      message:
        description: Commit message
        required: false


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Configure OpenHEXA CLI
        uses: blsq/openhexa-cli-action@v1
        with:
          workspace: "civ-pnlp-f01048"
          token: ${{ secrets.OH_TOKEN_CIV_PNLP }}
      - name: Push pipeline to OpenHEXA
        run: |
          openhexa pipelines push . --yes
        
