name: Push extract-metadata pipelines to OpenHEXA Workspace

on:
  push:
    paths:
      - ".github/workflows/push-iaso-extract-metadata.yml"
      - "iaso_extract_metadata/**"
      - "!iaso_extract_metadata/docs/**"
      - "!iaso_extract_metadata/docs/README.md"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Configure OpenHEXA CLI
        uses: blsq/openhexa-cli-action@v1
        with:
          workspace: "civ-pnlp-f01048"
          token: ${{ secrets.OH_TOKEN_CIV_PNLP }}
          
      - name: Push pipeline to OpenHEXA
        run: |
          openhexa pipelines push iaso_extract_metadata \
            --description "${{ github.event.head_commit.message }}" \
            --link "https://github.com/BLSQ/openhexa-pipelines-iaso/commit/${{ github.sha }}"
